id: P009424
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG03884
  title: ལམ་རིམ་གྱི་ཁྲིད་རྒྱུན་མནའ་གཏམ་གསེར་གྱི་ཕྲེང་བ་
  author: ''
  volumes:
    8f420a13710345edb4f31a020c4cbfd3:
      image_group_id: I00KG03938
      title: ''
      volume_number: 1
      total_pages: 24
      base_file: v001.txt
